### ISSUE TITLE
Unable to perform actions after changing successors

### ISSUE THREAD

**Issue by DamienOGE** [bryntum/odoo-support#34]
Bug introduced in bryntum_gantt_enterprise 14.0.1.2.0.
Any changes to a project to create successors using drag and drop in the calendar result in items being continually selected and deselected when hovered over. The same behaviour occurs when doing the operation within the task edit menu once the error has occurred. 
Selecting "Edit" on the task when possible will stop the select-deselect loop, but it will resume on next action that changes the calendar. Normal behaviour will only resume when the project page is reloaded or refreshed.
This was observed in Chrome, Firefox and Edge; I have not tested in Safari.

For most users this renders the module unuseable for projects that are not already predefined.

**Comment by javascript-programming** [comment]
I can not reproduce this. Do you have screenshots? Is it reproducible on https://odoo-gantt.bryntum.com/

Login with: demo/demo

**Comment by OffGridEuropeAdmin** [comment]
Apologies for the delay.
Issue is not reproduceable on https://odoo-gantt.bryntum.com/ .  I am operating on Odoo Enterprise 14.0 with bryntum_gantt_enterprise 14.0.1.2.0 . Is the linked demo running on the same?
Video of the issue is attached.
https://user-images.githubusercontent.com/81386519/134332272-a0415857-0921-4196-8f90-41eea05f8e95.mp4

**Comment by javascript-programming** [comment]
Yes Odoo14 but now on version bryntum_gantt_enterprise 14.0.1.2.4. 

I recommend you download a newer version of our module

**Comment by DamienOGE** [comment]
Resolved in version 14.0.1.2.4. Thanks!
